export const STATUS = {
  NEW: 'NEW',
  ACCEPTED: 'ACCEPTED',
  ON_THE_WAY: 'ON_THE_WAY',
  DELIVERED: 'DELIVERED',
  WAITING: 'WAITING',
  CANCELLED_BY_DELIVER: 'CANCELLED_BY_DELIVER',
  CANCELLED: 'CANCELLED',
  RE_CALL: 'RE_CALL',
};
