export const ENDPOINTS = {
  READ_PRODUCT_LIST: "/product/list/recommend",
  PRODUCT_LIST: "/product/list",
  CATEGORY_LIST_WITH_PRODUCTS: "category/list/with/product?limit=15&offset=1",
  PRODUCT_DETAIL: "/product/detail/",
  USER_LIST: "/user/list",
  REGISTER: "/user/register",
  LOGIN: "/user/login",
  VERIFY: "/user/verify",
  FORGOT_PASSWORD: "/user/forgot/password",
  LOGIN_REFRESH: "/user/login/refresh",
  RECOVER_FORGOT_PASSWORD: "/user/revocer/forgot/password",
  BANNER_LIST: "/banner/list",
  ORDER_LIST: "/order/list",
  PAYMENT_STATUS: "order/check/state",
  ORDER_CREATE: "/order/create",
  CATEGORY_LIST: "/category/list",
  REGION_LIST: "/region/list",
  USER_ADDRESS_UPDATE: "/user/address/update",
  USER_PROFILE: "/user/profile",
  USER_PROFILE_UPDATE: "/user/profile",
  USER_ADDRESS_DETAIL: "/user/address/detail",
  CATEGORY_SUB_LIST: "/category/sub/list/",
  PRODUCT_LIST_NEW: "product/list/new?limit=15&offset=1",
  PRODUCT_LIST_CHEAP: "product/list/cheap?limit=15&offset=1",
  PRODUCT_CHECK_ID: "product/check-ids",
};
